Revert "Fix autotimers to work with IPTV channels."
This reverts commit a075c41ebffa0cf67c3df1062daa9fd1db6624d2.

Box is unusable with this commit.

<   756.6693> 01:36:48.2614 [Task] >>> Error: [<Components.Task.FailedPostcondition object at 0xacc2d1d8>]
<   756.6695> 01:36:48.2616 [Task] job Components.Task.Job name=AutoTimer #tasks=74 completed with [<Components.Task.FailedPostcondition object at 0xacc2d1d8>] in Components.Task.Task name=FIM Speedway Grand Prix_14
<   756.6699> 01:36:48.2620 [Task] unrecoverable task failure
<   756.6699> 01:36:48.2620  AutoTimer
Error: [Failure instance: Traceback: <class 'SystemError'>: <built-in function eEPGCache_lookupEvent> returned a result with an exception set
/usr/lib/python3.10/threading.py:1009:_bootstrap_inner
/usr/lib/python3.10/threading.py:946:run
/usr/lib/python3.10/site-packages/twisted/_threads/_threadworker.py:47:work
/usr/lib/python3.10/site-packages/twisted/_threads/_team.py:182:doWork
--- <exception caught here> ---
/usr/lib/python3.10/site-packages/twisted/python/threadpool.py:244:inContext
/usr/lib/python3.10/site-packages/twisted/python/threadpool.py:260:<lambda>
/usr/lib/python3.10/site-packages/twisted/python/context.py:117:callWithContext
/usr/lib/python3.10/site-packages/twisted/python/context.py:82:callWithContext
/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimer.py:344:JobStart
/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimer.py:445:parseTimer
/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimer.py:355:getNonSearchableEvents
]<   756.6700> 01:36:48.2621
<   756.6721> 01:36:48.2643 [Skin] Processing screen 'MessageBoxSimple' from list 'MessageBoxSimple, MessageBox', position=(480, 532), size=(960 x 15) for module 'MessageBox'.
<   756.6890> 01:36:48.2812 [Screen] Warning: Skin is missing element 'icon' in <class 'Screens.MessageBox.MessageBox'>(AutoTimer
Error: [Failure instance: Traceback: <class 'SystemError'>: <built-in function eEPGCache_lookupEvent> returned a result with an exception set
/usr/lib/python3.10/threading.py:1009:_bootstrap_inner
/usr/lib/python3.10/threading.py:946:run
/usr/lib/python3.10/site-packages/twisted/_threads/_threadworker.py:47:work
/usr/lib/python3.10/site-packages/twisted/_threads/_team.py:182:doWork
--- <exception caught here> ---
/usr/lib/python3.10/site-packages/twisted/python/threadpool.py:244:inContext
/usr/lib/python3.10/site-packages/twisted/python/threadpool.py:260:<lambda>
/usr/lib/python3.10/site-packages/twisted/python/context.py:117:callWithContext
/usr/lib/python3.10/site-packages/twisted/python/context.py:82:callWithContext
/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimer.py:344:JobStart
/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimer.py:445:parseTimer
/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimer.py:355:getNonSearchableEvents
]).